// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmD6zo5AchkYNWpPCPi0SZgNOJ1LDbGKw',
    appId: '1:117721352592:web:ca5de99bb2fbf238d70b15',
    messagingSenderId: '117721352592',
    projectId: 'focusflow-3702f',
    authDomain: 'focusflow-3702f.firebaseapp.com',
    storageBucket: 'focusflow-3702f.firebasestorage.app',
    measurementId: 'G-9BLF8DLD1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD48P2xJQBcOSHJlXciXhsuDBwEOi9sSmY',
    appId: '1:117721352592:android:10ccaa2b4eb071e0d70b15',
    messagingSenderId: '117721352592',
    projectId: 'focusflow-3702f',
    storageBucket: 'focusflow-3702f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl5xJwFO-DZp6rCqL6wiH5Cf-u-1VF_Yc',
    appId: '1:117721352592:ios:9602021a3061b3fcd70b15',
    messagingSenderId: '117721352592',
    projectId: 'focusflow-3702f',
    storageBucket: 'focusflow-3702f.firebasestorage.app',
    iosBundleId: 'com.example.focusFlow',
  );
}
